### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by christianddietrich** [ggirelli/iFISH-probe-design#18]
**Describe the bug**
"ERROR 500: nothing here, sorry :(", when pressing "Submit" (Database: hg19 / Chromosome: chr1 / Start position: 10000 / End position: 100000)

```
(MainThread) Added task (0 tasks queued)
Traceback (most recent call last):
  File "/data/ifish/ifishvenv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/data/ifish/ifishvenv/bin/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "/data/ifish/ifishvenv/bin/bottle.py", line 3648, in wrapper
    return template(tpl_name, **tplvars)
  File "/data/ifish/ifishvenv/bin/bottle.py", line 3624, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/data/ifish/ifishvenv/bin/bottle.py", line 3413, in render
    self.execute(stdout, env)
  File "/data/ifish/ifishvenv/bin/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "/data/ifish/ifishvenv/lib/python3.7/site-packages/ifpd/sections/probe_design/views/query.tpl", line 124, in <module>
    %for rowi in range(min(query['candidate_table'].shape[0], max_probes)):
TypeError: '<' not supported between instances of 'str' and 'int'
```

**To Reproduce**
1. ifpd_mkdb -O /data/ifish/static/db/hg19 /data/ifish/iFISH.40mer.hg19 hg19 hg19
2. ifpd_serve -u 127.0.0.1 -s "/data/ifish/static"
3. Open "http://127.0.0.1:8080/"
4. Database: hg19 / Chromosome: chr1 / Start position: 10000 / End position: 100000 -> Submit

**Desktop (please complete the following information):**
- OS: Debian 9.9 x86_64 / Python 3.7.4 / iFISH 2.0.3
- Browser: Chrome 75 / Firefox 68

**Comment by ggirelli** [comment]
Hi there! Sorry for the late reply (I was on vacation 'til today). Thanks for reporting this bug. It is now fixed. Fix released in v2.0.3.post2 available now both on github and on pypi. I will now close this issue. Please post here any comments in case the fix is not fully effective. Cheers!
